version: "3.8"

services:

  sampobot:
    image: shell2016/sampobot
    container_name: sampobot
    build: .
    environment:
      - SAMPOBOT_TOKEN=${TOKEN}
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - LOGGING_FILE_NAME=${LOG_DIR}/bot.log
    volumes:
      - /home/$USER/sampobot_logs:${LOG_DIR}
    restart: always
    depends_on:
      - db

  db:
    image: postgres:${DB_VERSION}
    container_name: sampobot_db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"


