version: "3.9"

services:

  sampobot:
    image: shell2016/sampobot    # при деплое заменить на image: shell2016/sampobot
    container_name: sampobot
#    build: .  #    при деплое удалить строку
    environment:
      - SAMPOBOT_TOKEN=${TOKEN}
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_PROPERTIES_HIBERNATE_SHOW_SQL=false
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_TRANSACTION=info
      - LOGGING_FILE_NAME=${LOG_FILE}
    volumes:
      - /home/$USER/sampobot_logs:/app/logs
    restart: always
    depends_on:
      - db

  db:
    image: postgres:${DB_VERSION}
    container_name: sampobot_db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"


