bot:
  username: SampoRegistrationBot
  token: 5883387628:AAG5DDzl0_LAar-DCr6_gD71qE1XENm_e48
  admin:
    id: 528357712
    username: shell_2017

logging:
  level:
#    org:
#      springframework:
#        transaction: trace
    root: info
  file:
    name: /opt/bots/sampobot/logs/bot.log


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: sampobot
    password: 1636postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    properties:
      hibernate:
#        format_sql: true
#        show_sql: true
        hbm2ddl:
          auto: validate






