bot:
  username: SampoRegistrationBot
  token: 5883387628:AAG5DDzl0_LAar-DCr6_gD71qE1XENm_e48
  adminId: 528357712
  adminUsername: shell_201777777777

logging:
  level:
    org:
      springframework:
        transaction: trace
    root: info
  file:
    name: bot.log
    path: ./logs

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        hbm2ddl:
          auto: validate






