bot:
  username: ${BOT_USERNAME:SampoRegistrationBot}
  token: ${SAMPOBOT_TOKEN}
  admin:
    id: ${ADMIN_ID:528357712}
    username: ${ADMIN_USERNAME:shell_2017}

logging:
  level:
    org:
      springframework:
        transaction: trace
    root: info
  file:
    name: /home/${USER}/sampobot_logs/bot.log


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        hbm2ddl:
          auto: validate






