server:
  port: 8082
bot:
  admin: ${ADMIN_USERNAME}

logging:
  level:
    root: info

session:
  timeout: 10

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${SAMPOBOT_DB_NAME}
    username: ${SAMPOBOT_DB_USERNAME}
    password: ${SAMPOBOT_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
redis:
  host: ${REDIS_HOST}
  port: 6379
  password: ${REDIS_PASSWORD}
google:
  credentials:
    client-id:
    client-email:
    private-key:
    private-key-id:
  spreadsheets:
    spreadsheet-id:
    dump-cron: 0 0 * * * ?