package ru.michaelshell.sampo_bot.session;

public enum State {
    DEFAULT,
    PROMOTION_WAITING_FOR_USERNAME,
    EVENT_ADD_WAITING_FOR_NAME,
    EVENT_EDIT_WAITING_FOR_NAME,
    EVENT_ADD_WAITING_FOR_DATE,
    EVENT_EDIT_WAITING_FOR_DATE,
    EVENT_ADD_WAITING_FOR_INFO,
    EVENT_EDIT_WAITING_FOR_INFO,
    SET_ROLE_WAITING_FOR_NAME,
    COUPLE_REGISTER_WAITING_FOR_NAME,
    NOTIFY_ALL
}
